[2024-07-18T19:40:34.063+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-18T19:40:34.086+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: run_fill_procedure.end_process manual__2024-07-18T19:40:11.379675+00:00 [queued]>
[2024-07-18T19:40:34.094+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: run_fill_procedure.end_process manual__2024-07-18T19:40:11.379675+00:00 [queued]>
[2024-07-18T19:40:34.095+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-18T19:40:34.105+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): end_process> on 2024-07-18 19:40:11.379675+00:00
[2024-07-18T19:40:34.115+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'run_fill_procedure', 'end_process', 'manual__2024-07-18T19:40:11.379675+00:00', '--job-id', '507', '--raw', '--subdir', 'DAGS_FOLDER/create_and_fill_proc.py', '--cfg-path', '/tmp/tmpwilkhr1g']
[2024-07-18T19:40:34.117+0000] {standard_task_runner.py:91} INFO - Job 507: Subtask end_process
[2024-07-18T19:40:34.121+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=14408) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-18T19:40:34.122+0000] {standard_task_runner.py:63} INFO - Started process 14409 to run task
[2024-07-18T19:40:34.152+0000] {task_command.py:426} INFO - Running <TaskInstance: run_fill_procedure.end_process manual__2024-07-18T19:40:11.379675+00:00 [running]> on host 7c7e02e57379
[2024-07-18T19:40:34.220+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='run_fill_procedure' AIRFLOW_CTX_TASK_ID='end_process' AIRFLOW_CTX_EXECUTION_DATE='2024-07-18T19:40:11.379675+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-18T19:40:11.379675+00:00'
[2024-07-18T19:40:34.221+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-18T19:40:34.237+0000] {base.py:84} INFO - Using connection ID 'postgres_default' for task execution.
[2024-07-18T19:40:34.251+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-07-18T19:40:34.252+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-18T19:40:34.259+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=run_fill_procedure, task_id=end_process, run_id=manual__2024-07-18T19:40:11.379675+00:00, execution_date=20240718T194011, start_date=20240718T194034, end_date=20240718T194034
[2024-07-18T19:40:34.278+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-18T19:40:34.289+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-18T19:40:34.292+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
