[2024-07-16T20:56:17.852+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-16T20:56:17.884+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: csv_to_pgsql.extract_and_load_process manual__2024-07-16T20:56:07.852989+00:00 [queued]>
[2024-07-16T20:56:17.897+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: csv_to_pgsql.extract_and_load_process manual__2024-07-16T20:56:07.852989+00:00 [queued]>
[2024-07-16T20:56:17.899+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-16T20:56:17.919+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract_and_load_process> on 2024-07-16 20:56:07.852989+00:00
[2024-07-16T20:56:17.944+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'csv_to_pgsql', 'extract_and_load_process', 'manual__2024-07-16T20:56:07.852989+00:00', '--job-id', '318', '--raw', '--subdir', 'DAGS_FOLDER/from_csv_to_pgsql.py', '--cfg-path', '/tmp/tmpqlr35xpc']
[2024-07-16T20:56:17.948+0000] {standard_task_runner.py:91} INFO - Job 318: Subtask extract_and_load_process
[2024-07-16T20:56:17.949+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=3886) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-16T20:56:17.950+0000] {standard_task_runner.py:63} INFO - Started process 3889 to run task
[2024-07-16T20:56:18.020+0000] {task_command.py:426} INFO - Running <TaskInstance: csv_to_pgsql.extract_and_load_process manual__2024-07-16T20:56:07.852989+00:00 [running]> on host 347bc1cf7978
[2024-07-16T20:56:18.107+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='csv_to_pgsql' AIRFLOW_CTX_TASK_ID='extract_and_load_process' AIRFLOW_CTX_EXECUTION_DATE='2024-07-16T20:56:07.852989+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-16T20:56:07.852989+00:00'
[2024-07-16T20:56:18.108+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-16T20:56:26.888+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-16T20:56:26.890+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/from_csv_to_pgsql.py", line 103, in extract_and_load_task
    df.write.jdbc(url=postgres_uri, table=f'ds.{file_name}', mode="append", properties=properties, schema=f'schema_{file_name}')
TypeError: DataFrameWriter.jdbc() got an unexpected keyword argument 'schema'
[2024-07-16T20:56:26.901+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=csv_to_pgsql, task_id=extract_and_load_process, run_id=manual__2024-07-16T20:56:07.852989+00:00, execution_date=20240716T205607, start_date=20240716T205617, end_date=20240716T205626
[2024-07-16T20:56:26.915+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 318 for task extract_and_load_process (DataFrameWriter.jdbc() got an unexpected keyword argument 'schema'; 3889)
[2024-07-16T20:56:26.942+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-16T20:56:26.962+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-16T20:56:26.964+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
