[2024-07-16T21:01:12.840+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-16T21:01:12.866+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: csv_to_pgsql.extract_and_load_process manual__2024-07-16T21:01:05.810033+00:00 [queued]>
[2024-07-16T21:01:12.873+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: csv_to_pgsql.extract_and_load_process manual__2024-07-16T21:01:05.810033+00:00 [queued]>
[2024-07-16T21:01:12.874+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-16T21:01:12.884+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract_and_load_process> on 2024-07-16 21:01:05.810033+00:00
[2024-07-16T21:01:12.890+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'csv_to_pgsql', 'extract_and_load_process', 'manual__2024-07-16T21:01:05.810033+00:00', '--job-id', '322', '--raw', '--subdir', 'DAGS_FOLDER/from_csv_to_pgsql.py', '--cfg-path', '/tmp/tmp46ukq5u5']
[2024-07-16T21:01:12.893+0000] {standard_task_runner.py:91} INFO - Job 322: Subtask extract_and_load_process
[2024-07-16T21:01:12.894+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=4328) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-16T21:01:12.897+0000] {standard_task_runner.py:63} INFO - Started process 4329 to run task
[2024-07-16T21:01:12.945+0000] {task_command.py:426} INFO - Running <TaskInstance: csv_to_pgsql.extract_and_load_process manual__2024-07-16T21:01:05.810033+00:00 [running]> on host 347bc1cf7978
[2024-07-16T21:01:13.023+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='csv_to_pgsql' AIRFLOW_CTX_TASK_ID='extract_and_load_process' AIRFLOW_CTX_EXECUTION_DATE='2024-07-16T21:01:05.810033+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-16T21:01:05.810033+00:00'
[2024-07-16T21:01:13.024+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-16T21:01:17.125+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-16T21:01:17.126+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/from_csv_to_pgsql.py", line 99, in extract_and_load_task
    df = spark.read.csv(f'/opt/airflow/files/{file}', sep=';', header=True, schema=f'schema_{file_name}')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/sql/readwriter.py", line 701, in csv
    self._set_opts(
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/sql/readwriter.py", line 51, in _set_opts
    self.schema(schema)  # type: ignore[attr-defined]
    ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/sql/readwriter.py", line 155, in schema
    self._jreader = self._jreader.schema(schema)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/py4j/java_gateway.py", line 1322, in __call__
    return_value = get_return_value(
                   ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/errors/exceptions/captured.py", line 185, in deco
    raise converted from None
pyspark.errors.exceptions.captured.ParseException: 
[PARSE_SYNTAX_ERROR] Syntax error at or near end of input.(line 1, pos 19)

== SQL ==
schema_ft_balance_f
-------------------^^^

[2024-07-16T21:01:17.149+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=csv_to_pgsql, task_id=extract_and_load_process, run_id=manual__2024-07-16T21:01:05.810033+00:00, execution_date=20240716T210105, start_date=20240716T210112, end_date=20240716T210117
[2024-07-16T21:01:17.162+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 322 for task extract_and_load_process (
[PARSE_SYNTAX_ERROR] Syntax error at or near end of input.(line 1, pos 19)

== SQL ==
schema_ft_balance_f
-------------------^^^
; 4329)
[2024-07-16T21:01:17.183+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-16T21:01:17.213+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-16T21:01:17.218+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
